# config.yaml

# Configuration de la grille
CELL_SIZE: 10
GRID_WIDTH: 800
GRID_HEIGHT: 600

# Couleurs
colors:
  WHITE: [255, 255, 255]
  BLACK: [0, 0, 0]
  GRAY: [200, 200, 200]
  LIGHT_GRAY: [220, 220, 220]
  HIGHLIGHT: [150, 150, 150]
